# Numpy Task

### Instructions:
- Answer the following questions using NumPy only.
- Do not use Python loops unless explicitly stated.

## Part 1: Creating Arrays (3 Questions)


####  1) Create a NumPy array that contains all even numbers between 10 and 50 (inclusive).


In [13]:
arr=np.arange(10,51,2)
print(arr)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]





#### 2) Create an array of shape (3, 4) filled with ones, then change all values in the last column to 0.



In [14]:
arr = np.ones((3, 4))
arr[:, :-1]=0
print(arr)

[[0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]]





#### 3) Create a NumPy array of 5 equally spaced numbers between -1 and 1.

In [16]:
arr=np.linspace(-1,1,5)
print(arr)

[-1.  -0.5  0.   0.5  1. ]


## Part 2: Array Properties (3 Questions)

#### 1) Create array and then 
- Find its shape

- Number of elements

- Data type

In [3]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(arr.shape)
print(arr)
print(arr.dtype)

(2, 3)
[[1 2 3]
 [4 5 6]]
int64


#### 2) Create a random array of size 10 and find:
- minimum value

- maximum value

- standard deviation

In [4]:
a=np.random.rand(2,2)
print(a)
print(a.min())
print(a.max())
print(a.std())

[[0.18383882 0.09373946]
 [0.9570823  0.60784444]]
0.09373945963190611
0.9570822990168855
0.34617878475536723


#### 3) What is the difference between arr.size and arr.shape?

- Explain using an example.

In [10]:
print(arr.shape,{",number of elemnent =  "},arr.size)


(6,) {',number of elemnent =  '} 6


## Part 3: Mathematical Operations & ufuncs (3 Questions)

#### 1) Create a new array that contains the square of each element without using loops.

In [5]:
# Given 

arr = np.array([1, 4, 9, 16, 25,36])
print(np.sqrt(arr))
a=np.random.rand(3,3)

[1. 2. 3. 4. 5. 6.]


#### 2) Compute the mean and sum of all values in a 3×3 random matrix.

In [6]:

print("Mean ",a.mean(),"sum =",a.sum())
print("Random 3x3 matrix:\n", a)

Mean  0.46465479109409635 sum = 4.181893119846867
Random 3x3 matrix:
 [[0.59219782 0.31261171 0.38782788]
 [0.44407889 0.13370084 0.5115245 ]
 [0.73136765 0.45243536 0.61614847]]


#### 3) Compute the mean and sum of all values in a 3×3 random matrix.

In [ ]:

print("Mean ",a.mean(),"sum =",a.sum())
print("Random 3x3 matrix:\n", a)

## Part 4: Indexing, Slicing & Boolean Indexing (4 Questions)

#### 1) Extract the middle four elements using slicing.

In [ ]:
# Given 
arr = np.array([10, 20, 30, 40, 50, 60])

arr = np.array([10, 20, 30, 40, 50, 60])
print(arr[:-1]) #all 
print(arr[0:4])
print(arr[1:5])

#### 2) From the same array, extract all values greater than 25.

In [7]:
print(arr[arr > 25])  


[ 1  4  9 16]


#### 3) Modify the array so that all values less than 30 become 0.

In [ ]:

arr[arr > 30]=0 
print(arr)

#### 4) When would slicing be better than Boolean indexing?
Give one example.

## Part 5: Random Numbers & Performance (3 Questions)

#### 1) Generate a reproducible array of 15 random integers between 1 and 100.

In [ ]:

np.random.seed(42)
arr = np.random.randint(1, 101, size=15)
print( arr)


#### 2) Create two arrays:

- one using a Python loop

- one using NumPy vectorization 

``to add 10 to each element.``

**Which one is faster and why?**

#### 2) Create two arrays:

- one using a Python loop

- one using NumPy vectorization 

``to add 10 to each element.``

**Which one is faster and why?**

In [ ]:
start = time.time()

result_vector = arr + 10     

end = time.time()

print("Time with NumPy vectorization:", end - start)


In [8]:

import time

py_arr = list(range(1, 11))

# loop
start_time = time.time()

py_result = []
for x in py_arr:
    py_result.append(x + 10)

end_time = time.time()
print("Python loop result:", py_result)
print("Python loop time:", end_time - start_time, "seconds")

Python loop result: [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
Python loop time: 8.20159912109375e-05 seconds


#### 4) Why is `np.random.seed()` important in data science experiments?

## Part 6: Linear Algebra & Matrix Operations (2 Questions)

#### 1) Compute the determinant and inverse of a square matrix of your choice.

In [ ]:
A = np.array([[2, 1, 3],
              [0, 1, 4],
              [5, 2, 1]])

# )   1-(determinant)
det_A = np.linalg.det(A)
print("Determinant of A:", det_A)

# 2- (inverse)
if det_A != 0:
    inv_A = np.linalg.inv(A)
    print("Inverse of A:\n", inv_A)
else:
    print("Matrix is singular, cannot compute inverse.")


#### 2) What is the difference between:

- element-wise multiplication

- matrix multiplication
in NumPy?

## Bonus (Optional – Mindset Question)

#### How does NumPy help a Data Analyst think in a vectorized and mathematical way instead of a procedural one?